name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.18.0"

      - name: Install dependencies
        run: npm install

      - name: Add npm global bin to PATH
        run: echo "$(npm config get prefix)/bin" >> $GITHUB_PATH

      - name: Install Expo CLI
        run: npm install -g @expo/cli

      - name: Verify Expo CLI Installation
        run: expo --version

      - name: Build APK
        run: expo build:android -t apk --no-wait
